# Generated by Django 2.2.12 on 2020-12-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker_app', '0006_auto_20201208_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prices',
            field=models.CharField(default={}, max_length=255555),
        ),
    ]
