# Generated by Django 2.2.12 on 2020-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker_app', '0007_item_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prices',
            field=models.TextField(default={}),
        ),
    ]
