# Generated by Django 3.1.4 on 2020-12-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker_app', '0008_auto_20201208_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prices',
            field=models.JSONField(),
        ),
    ]
